#!/bin/bash
# Run the PDP-8 ISA-level simulator

clear
make clean
make all
echo "_______________ OUTPUT ____________________"
./main
echo "__________ GENERATED TRACEFILE ____________"
cat tracefile.din
