#!/bin/bash
# Run the PDP-8 ISA-level simulator

clear
make clean
make all
echo "_____________ TEST FILE ___________________"
cat test.mem
echo "______________ WARNINGS ___________________"
./main
echo "__________ GENERATED TRACEFILE ____________"
cat tracefile.din
